services:
  api:
    build:
      context: ../trip-api
      dockerfile: ../docker/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
    volumes:
      - ../trip-api:/var/www/html
    command: sh -c "composer install && \
      php artisan key:generate && \
      mkdir -p database && \
      touch database/trip-manager.sqlite && \
      php artisan migrate --force && \
      php artisan serve --host=0.0.0.0 --port=8000"
  
  web:
    build:
      context: ../trip-web
      dockerfile: ../docker/Dockerfile.web
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ../trip-web:/app
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - api